magnum_src_dir: "src/opendev.org/openstack/magnum"

magnum_repository: openstackmagnum

# NOTE: By default, stable images are not built if they already exist.
# Assigning dev=true property for heat container agent images means that a new
# image is re-built and pushed under the same tag every time.
heat_container_agent_images:
  - tag: victoria-stable-1
  - tag: wallaby-stable-1

kubernetes_versions:
  - version: v1.15.12

kubernetes_images:
  - name: kubernetes-apiserver
  - name: kubernetes-controller-manager
  - name: kubernetes-kubelet
  - name: kubernetes-scheduler
  - name: kubernetes-proxy

helm_versions:
  - version: v2.16.6
  - version: v3.2.0

cluster_autoscaler_versions:
  - version: 1.18.3
  - version: 1.19.1
  - version: 1.20.0
  - version: 1.21.0
  - version: 1.22.0
  - version: 1.23.0
